### ISSUE TITLE
The height of the minibuffer cannot be adjusted using the latest dash.el

### ISSUE THREAD

**Issue by shanyouli** [kiennq/emacs-mini-modeline#12]
Today I updated my emacs package, restart emacs and found that I can't use the M-x run command because it can't display the list in the minibuffer, the picture looks like this:
![2019-10-04-120300_872x151_scrot](https://user-images.githubusercontent.com/48723272/66180301-16e7f680-e69f-11e9-851b-c71973578dbc.png)
And what I need is the following picture, because I use the ivy package。
![2019-10-04-120630_691x163_scrot](https://user-images.githubusercontent.com/48723272/66180380-6a5a4480-e69f-11e9-8b1d-9a8af9142086.png)
M-x works fine when I change the version of dash.el to 2.12
![2019-10-04-121119_841x261_scrot](https://user-images.githubusercontent.com/48723272/66180576-1b60df00-e6a0-11e9-9d37-d47cf4cf910b.png)
Do you have time to make mini-modeline have the same effect as the latest version of dash.el and version 2.12 of dash.el?

**Comment by kiennq** [comment]
Did it work with normal command? Can you provide a mini emacs config that I can try to repro?
I'm using `dash-20190920.1035` and it seems working fine

**Comment by shanyouli** [comment]
@kiennq, Yes, it must be working。
At first I found out that there is a problem with mini-modeline, I am using emacs version is 27.0.50, its corresponding commit is "56985dd8a69fc2729422cf8f95efbd03ee6b021", I use the minimized configuration as follows
```emacs-lisp
(load-path "~/dash.el")
(push "~/dash.el" load-path)
(load "~/Git/emacs-mini-modeline/mini-modeline")
(push "~/.emacs.d/.cache/elpa/ivy-20190919.1331" load-path)
(push "~/.emacs.d/.cache/elpa/swiper-20190822.1708" load-path)
(require 'mini-modeline)
(require 'swiper)
(require 'counsel)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-s") 'swiper)
```
The Problem recurrence，So I tried to install emacs-26.3, test again, the problem still exists, But I found that pressing twice can show the options（PS：I can't reproduce this myself).
After that I will dash.el more to the 2.12 version, test it to see the options。
Finally submitted this question。

Now, I am trying a new minimal configuration in emacs26.3 and found that the problem does not exist.
```emacs-lisp
(push "~/Work/emacs-test/dash.el" load-path)
(push "~/Work/emacs-test/swiper" load-path)
(push "~/Work/emacs-test/emacs-mini-modeline" load-path)

(require 'mini-modeline)
(require 'swiper)
(require 'counsel)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-s") 'swiper)
```
I guess the main reason why I can't work before is to re-compile mini-modeline, dash.el, ivy .etc after downgrading emacs.
Because I returned to [emacs27.0.50](https://github.com/emacs-mirror/emacs/tree/56985dd8a69fc2729422cf8f95efbd03ee6b021e), the problem is still.
This issue is not related to the dash version, but is related to the emacs version.

**Comment by kiennq** [comment]
Seem like a regression of #11, we've advised minibuffer setup and exit hook with `resize-mini-windows`.
That seems break ivy.

**Comment by kiennq** [comment]
@QiangF Do you have objection if I'm removing those hooks?
It interferes with `Counsel-M-x` and also I'm not sure if it's working efficiently in `mini-modeline` too.

@shanyouli: can you try [this branch](https://github.com/kiennq/emacs-mini-modeline/tree/bug/12) and see if the problem persists?

**Comment by shanyouli** [comment]
This bug was fixed in `bug/12`. If there is no other place in my problem that needs my help, I will close the issue after one day. 
By the way, this package is very good and thank you for taking the time to solve my problem.

**Comment by kiennq** [comment]
You're welcome. 😸

**Comment by QiangF** [comment]
> @QiangF Do you have objection if I'm removing those hooks?
> It interferes with `Counsel-M-x` and also I'm not sure if it's working efficiently in `mini-modeline` too.


@kiennq No problem. My issue only happens with pyim, I will advice the pyim function instead.

**Comment by kiennq** [comment]
@QiangF: Thanks. Also can you try if pyim works with latest version first?
From what I see, #10 happens when `resize-mini-windows` set to `grow-only`. Once it's set to `t` of `nil`, with your new duration code, the mini buffer will not be quickly resized.
From its document, it makes sense since only `grow-only` looks at echo area (which is normally blank with `mini-modeline`).

**Comment by QiangF** [comment]
No, the latest version still doesn't prevent the resizing during consecutive messaging.

    (eval (progn
            (setq resize-mini-windows t)
            (setq mini-modeline-truncate-p nil)
            (run-at-time 0.3 nil (lambda () (message  "a\nb\nc")))
            (run-at-time 0.6 nil (lambda () (message  "a\nb\nc")))
            (run-at-time 0.9 nil (lambda () (message  "a\nb\nc")))))

As you see in the above test code, when the minibuffer resizes, only the first of the three line is left. The minibuffer must have been resized somewhere other than in mini-modeline-display.

**Comment by kiennq** [comment]
Doesn't seems happen to me.
![4195b894-92a4-4041-9d05-709fe53324e1](https://user-images.githubusercontent.com/2631472/66286726-a5fa4600-e90d-11e9-950f-68065e7fc24a.gif)

It must has been resized somewhere else.

**Comment by QiangF** [comment]
I will report back once I found the real cause. Thank you!
